In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.autograd as tgrad
import numpy as np
import os
import time

import utils

import networks

import matplotlib.pyplot as plt

import importlib

In [2]:
os.environ['KMP_DUPLICATE_LIB_OK']='True'
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(torch.cuda.is_available())
# torch.set_default_tensor_type(torch.DoubleTensor)
print(device)

if device == 'cuda': 
    print(torch.cuda.get_device_name())

True
cuda


# Data Sampling
Here in our case, the system is European Call Option PDE and the physical information about the system consists of Boundary Value conditions, final Value conditions and the PDE itself.

In [3]:
K = 50
r = 0.035
sigma = 0.2
T = 1
S_range = [0, int(5*K)]
t_range = [0, T]
gs = lambda x: np.fmax(x-K, 0)

# Build Neural Network

In [4]:
pinn = networks.FeedforwardNeuralNetwork(2, 50, 1, 8)
pinn.cuda()

FeedforwardNeuralNetwork(
  (layers): ModuleList(
    (0): Linear(in_features=2, out_features=50, bias=True)
    (1-7): 7 x Linear(in_features=50, out_features=50, bias=True)
  )
  (output): Linear(in_features=50, out_features=1, bias=True)
  (relu): ReLU()
)

In [5]:
import torchimize
# parallel levenberg-marquardt for several optimization problems at multiple costs
# from torchimize.functions import lsq_lma_parallel
# coeffs_list = lsq_lma_parallel(
#                     p = initials_batch,
#                     function = multi_cost_fun_batch,
#                     jac_function = multi_jac_fun_batch,
#                     args = (other_args,),
#                     wvec = torch.ones(5, device='cuda', dtype=initials_batch.dtype),
#                     ftol = 1e-8,
#                     ptol = 1e-8,
#                     gtol = 1e-8,
#                     meth = 'marq',
#                     max_iter = 40,
#                 )

n_epochs = 30000
lossFunction = nn.MSELoss()

from torchimize.functions import lsq_lma
# coeffs_list = lsq_lma(fnn.parameters(), function=lossFunction)
optimizer = optim.Adam(pinn.parameters(), lr=0.00003)

samples = {"pde": 5000, "bc":500, "fc":500}

# Modelling

- For each iteration in the training loop, we are sampling data for the three physical conditions of the PDE.
- Then we are calculating the loss three times on the same model, accumulating them into a combined objective function to be minimised for the Neural Network.
- The first loss is the differential equation loss. Here we are trying to minimise the PDE by calculating gradients and forming the PDE itself.
- The remaining losses are calculated for boundary value and initial value conditions for the PDE.
- Mean Squared Error loss function `nn.MSELoss()` is chosen as the criterion to be minimised and 
- Adam optimizer `nn.optim.Adam(lr=3e-5)` with a learning rate of 0.00003 is chosen for performing the weight updates.

In [6]:
loss_hist = []
start_time = time.time()

for epoch in range(n_epochs):
    
    bc_st_train, bc_v_train, n_st_train, n_v_train = \
    utils.trainingData(K, 
                       r, 
                       sigma, 
                       T, 
                       S_range[-1], 
                       S_range, 
                       t_range, 
                       gs, 
                       samples['bc'], 
                       samples['fc'], 
                       samples['pde'], 
                       RNG_key=123)
    # save training data points to tensor and send to device
    n_st_train = torch.from_numpy(n_st_train).float().requires_grad_().to(device)
    n_v_train = torch.from_numpy(n_v_train).float().to(device)
    
    bc_st_train = torch.from_numpy(bc_st_train).float().to(device)
    bc_v_train = torch.from_numpy(bc_v_train).float().to(device)
    
    
    # PDE Round
    y1_hat = pinn(n_st_train)
    grads = tgrad.grad(y1_hat, n_st_train, grad_outputs=torch.ones(y1_hat.shape).cuda(), retain_graph=True, create_graph=True, only_inputs=True)[0]
    # print(grads)
    dVdt, dVdS = grads[:, 0].view(-1, 1), grads[:, 1].view(-1, 1)
    grads2nd = tgrad.grad(dVdS, n_st_train, grad_outputs=torch.ones(dVdS.shape).cuda(), create_graph=True, only_inputs=True)[0]
    # print(grads2nd)
    d2VdS2 = grads2nd[:, 1].view(-1, 1)
    S1 = n_st_train[:, 1].view(-1, 1)
    pde_loss = lossFunction(-dVdt, 0.5*((sigma*S1)**2)*d2VdS2 + r*S1*dVdS - r*y1_hat)
    
    
    # conditions Round
    y21_hat = pinn(bc_st_train)
    bc_loss = lossFunction(bc_v_train, y21_hat)
    
    
    # Backpropagation and Update
    optimizer.zero_grad()
    combined_loss = pde_loss + bc_loss
    combined_loss.backward()
    optimizer.step()
    
    loss_hist.append(combined_loss.item())
    if epoch % 500 == 0:
        print(f'{epoch}/{n_epochs} PDE Loss: {pde_loss.item():.5f}, BC Loss: {bc_loss.item():.5f}, total loss: {combined_loss.item():5f}, minimum loss: {min(loss_hist):.5f}')

end_time = time.time()
print('run time:', end_time - start_time)

0/30000 PDE Loss: 0.00001, BC Loss: 16884.71484, total loss: 16884.714844, minimum loss: 16884.71484
500/30000 PDE Loss: 0.03020, BC Loss: 4542.60107, total loss: 4542.631348, minimum loss: 4542.63135
1000/30000 PDE Loss: 0.00743, BC Loss: 164.39935, total loss: 164.406784, minimum loss: 164.40678
1500/30000 PDE Loss: 0.80311, BC Loss: 149.07271, total loss: 149.875824, minimum loss: 149.87582
2000/30000 PDE Loss: 11.71070, BC Loss: 104.63575, total loss: 116.346451, minimum loss: 116.34645
2500/30000 PDE Loss: 26.29072, BC Loss: 60.95219, total loss: 87.242905, minimum loss: 87.24290
3000/30000 PDE Loss: 24.21111, BC Loss: 30.84291, total loss: 55.054024, minimum loss: 55.05402
3500/30000 PDE Loss: 11.13585, BC Loss: 8.17955, total loss: 19.315405, minimum loss: 19.31540
4000/30000 PDE Loss: 1.23236, BC Loss: 0.59297, total loss: 1.825328, minimum loss: 1.82533
4500/30000 PDE Loss: 0.02145, BC Loss: 0.04019, total loss: 0.061644, minimum loss: 0.04907
5000/30000 PDE Loss: 0.00084, BC 

In [7]:
print(utils.test(device, pinn))

tensor([-0.0002], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([0.0004], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([0.], device='cuda:0')
tensor([0.], device='cuda:0')
0.16016879677772522
